spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: "@MacBook1"
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
